import { useState } from "react";
import { Pencil } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select";
import { moneyBR, type FinanceContract } from "@/lib/finance";
import { commercialLabels, inventoryStatus } from "@/lib/financeAnalytics";
import { normalizeString } from "@/lib/utils";
export function FinanceInventory({ items, canWrite, onEdit }: { items: FinanceContract[]; canWrite: boolean; onEdit: (item: FinanceContract) => void }) {
  const [search, setSearch] = useState(""); const [type, setType] = useState("all"); const [kind, setKind] = useState("all");
  const filtered = items.filter((i) => normalizeString(i.title).includes(normalizeString(search)) && (type === "all" || i.commercial_type === type) && (kind === "all" || i.item_type === kind));
  const day = (value: string | null) => value ? value.slice(0, 10).split("-").reverse().join("/") : "A definir";
  return <section className="space-y-4"><h2 className="text-xl font-bold">Contratos e inventário</h2><div className="flex flex-wrap gap-3"><Input className="min-w-0 flex-1" aria-label="Buscar contrato" placeholder="Buscar contrato" value={search} onChange={(e) => setSearch(e.target.value)} /><Select value={kind} onValueChange={setKind}><SelectTrigger className="w-full sm:w-52" aria-label="Tipo de espaço"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Todos os tipos</SelectItem><SelectItem value="evento">Eventos patrocinados</SelectItem><SelectItem value="anuncio">Espaços publicitários</SelectItem></SelectContent></Select><Select value={type} onValueChange={setType}><SelectTrigger className="w-full sm:w-40" aria-label="Filtro de contratação"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Toda contratação</SelectItem>{Object.entries(commercialLabels).map(([k, l]) => <SelectItem key={k} value={k}>{l}</SelectItem>)}</SelectContent></Select></div><p className="text-xs text-muted-foreground">{filtered.length} contratos · {filtered.filter((i) => inventoryStatus(i) === "Em veiculação").length} em veiculação</p>{filtered.length === 0 ? <p className="py-6 text-sm text-muted-foreground">Nenhum contrato por aqui. Tente outro filtro.</p> : <ul className="max-h-[65dvh] overflow-y-auto divide-y divide-border">{filtered.map((i) => <li key={`${i.item_type}-${i.item_id}`} className="flex justify-between items-start gap-3 py-4"><div className="min-w-0 space-y-2"><p className="break-words font-bold">{i.title}</p><div className="flex flex-wrap gap-2"><Badge variant="outline">{commercialLabels[i.commercial_type]}</Badge><Badge variant="secondary">{inventoryStatus(i)}</Badge></div><p className="text-xs text-muted-foreground">{i.item_type === "anuncio" ? "Espaço publicitário" : "Evento patrocinado"} · Referência {moneyBR(i.reference_amount_cents)}</p><p className="text-xs text-muted-foreground">{day(i.starts_on)} → {day(i.ends_on ?? i.highlight_until)}</p>{i.notes && <p className="break-words text-sm">{i.notes}</p>}</div>{canWrite && <Button size="icon" variant="ghost" aria-label={`Editar contrato de ${i.title}`} title="Editar contrato" onClick={() => onEdit(i)}><Pencil className="h-4 w-4" /></Button>}</li>)}</ul>}</section>;
}