import { beforeEach, describe, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { HelmetProvider } from "react-helmet-async";
import { buildPitchContent } from "../../../supabase/functions/commercial-pitch/content";
import AdminPitchComercial from "../AdminPitchComercial";

const mocks = vi.hoisted(() => ({ call: vi.fn(), allowed: true, userId: "test-user" }));
vi.mock("@/lib/edge", () => ({ callEdge: mocks.call }));
vi.mock("@/contexts/AuthContext", () => ({ useAuth: () => ({ user: { id: mocks.userId }, mustChangePassword: false }) }));
vi.mock("@/hooks/useAppPermissions", () => ({ useAppPermissions: () => ({ hasPermission: () => mocks.allowed }) }));
const page = () => <HelmetProvider><AdminPitchComercial /></HelmetProvider>;

describe("pitch comercial", () => {
  beforeEach(() => { mocks.allowed = true; mocks.userId = "test-user"; mocks.call.mockReset(); });
  it("calcula projeções sem dupla contagem ou confundir saldo com lucro", () => {
    const content = buildPitchContent();
    expect(content.scenarios.map((s) => s.revenue)).toEqual([1960, 5880, 11760]);
    expect(content.scenarios.map((s) => s.afterMarketing)).toEqual([1460, 5130, 10760]);
    expect(content.scenarios.map((s) => s.pushRevenue)).toEqual([600, 1800, 3600]);
    expect(content.scenarios.map((s) => s.phase)).toEqual(["Fase Inicial", "Fase de Expansão", "Fase Consolidada"]);
    expect(content.scenarios.every((s) => s.pushes === s.regions * content.push.packageSends)).toBe(true);
    expect(content.push.packagePrice).toBe(content.pushTicket * content.push.packageSends);
    expect(content.push.requirements).toContain("ainda sem disparos ativados");
    expect(content.anchor.tiers.map(({ slots, min, max }) => ({ slots, min, max }))).toEqual([{ slots: 1, min: 800, max: 1000 }, { slots: 2, min: 400, max: 500 }]);
    expect([content.anchor.monthlyMin, content.anchor.monthlyMax]).toEqual([1600, 2000]);
    expect(content.anchor.billing).toContain("Recorrência mensal");
    expect(content.anchor.phases.map((phase) => phase.title)).toEqual(["Teaser", "Aquecimento", "Reta Final"]);
    expect(content.formats.find((format) => format.title === "Anunciante Master")).toMatchObject({ min: 800, max: 1000, priceSuffix: "/mês" });
    expect(content.formats.find((format) => format.title === "Sub-Masters / Co-Patrocinadores")).toMatchObject({ min: 400, max: 500, priceSuffix: "/mês cada" });
    expect(content.formats.some((format) => format.cycle.includes("trimestral"))).toBe(false);
    expect(content.anchor.disclaimer).toContain("Não está somado à projeção mensal");
    expect(content.scenarios.every((s) => s.placements / s.regions === 3)).toBe(true);
    expect(content.disclaimer).toContain("não é lucro líquido");
    expect(content.brandPositioning).toContain("produto oficial");
    expect(content.brandPositioning).toContain("Rio de Janeiro");
    expect(content.monetization).toContain("venda profissional de espaços publicitários");
    expect(content.projectionBasis).toContain("não taxas simbólicas");
    expect(content.scenarios.every((s) => s.placementRevenue > s.marketing)).toBe(true);
  });
  it("só exibe após conferência, permite bloquear e limpa o campo", async () => {
    mocks.call.mockResolvedValue({ content: buildPitchContent(), expiresInSeconds: 900 });
    render(page());
    expect(screen.queryByText("Projeção de receita mensal")).not.toBeInTheDocument();
    expect(screen.queryByRole("heading", { name: buildPitchContent().anchor.title })).not.toBeInTheDocument();
    fireEvent.change(screen.getByLabelText("Senha do pitch"), { target: { value: "synthetic-test-input" } });
    fireEvent.click(screen.getByRole("button", { name: "Abrir pitch" }));
    await screen.findByText("Projeção de receita mensal");
    expect(screen.getByRole("heading", { name: /^Coé a Boa\?$/ })).toBeInTheDocument();
    expect(screen.getByText(buildPitchContent().monetization)).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Notificações Push Regionais" })).toBeInTheDocument();
    expect(screen.getByRole("columnheader", { name: /Fase de Expansão/ })).toBeInTheDocument();
    expect(screen.getByRole("rowheader", { name: "Receita de pushes patrocinados" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { level: 2, name: buildPitchContent().anchor.title })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "1 Anunciante Master" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "2 Sub-Masters / Co-Patrocinadores" })).toBeInTheDocument();
    expect(screen.getByText(buildPitchContent().anchor.billing)).toBeInTheDocument();
    expect(screen.queryByText(/Pacote trimestral/)).not.toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Banner âncora prioritário na Home" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Contagem regressiva para o evento" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /01\s*Teaser/ })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /02\s*Aquecimento/ })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: /03\s*Reta Final/ })).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Bloquear" }));
    expect(screen.queryByRole("heading", { name: buildPitchContent().anchor.title })).not.toBeInTheDocument();
    expect(screen.queryByText("Projeção de receita mensal")).not.toBeInTheDocument();
    expect(screen.getByLabelText("Senha do pitch")).toHaveValue("");
  });
  it("mantém fechado quando a senha é recusada", async () => {
    mocks.call.mockRejectedValue(new Error("Senha incorreta. Confira e tente novamente."));
    render(page());
    fireEvent.change(screen.getByLabelText("Senha do pitch"), { target: { value: "synthetic-test-input" } });
    fireEvent.click(screen.getByRole("button", { name: "Abrir pitch" }));
    await screen.findByRole("alert");
    expect(screen.queryByText("Projeção de receita mensal")).not.toBeInTheDocument();
  });
  it("não solicita conteúdo quando a conta não possui acesso", () => {
    mocks.allowed = false;
    render(page());
    expect(screen.getByLabelText("Senha do pitch")).toBeDisabled();
    expect(screen.getByRole("button", { name: "Abrir pitch" })).toBeDisabled();
    expect(mocks.call).not.toHaveBeenCalled();
    expect(screen.queryByText(buildPitchContent().brandPositioning)).not.toBeInTheDocument();
  });
  it("remove conteúdo ao trocar de conta", async () => {
    mocks.call.mockResolvedValue({ content: buildPitchContent(), expiresInSeconds: 900 });
    const view = render(page());
    fireEvent.change(screen.getByLabelText("Senha do pitch"), { target: { value: "synthetic-test-input" } });
    fireEvent.click(screen.getByRole("button", { name: "Abrir pitch" }));
    await screen.findByText("Projeção de receita mensal");
    mocks.userId = "other-test-user";
    view.rerender(page());
    await waitFor(() => expect(screen.queryByText("Projeção de receita mensal")).not.toBeInTheDocument());
  });
});